### ISSUE TITLE
Can this software compare GO pathway?

### ISSUE THREAD

**Issue by tianxiahuihui** [SabaLab/diffEnrich#1]
Dear Sir:

Thank you for your software. I want to compare two gene lists in the GO pathway. How can I do it with this software?

Thank you.

**Comment by hsmith9002** [comment]
@tianxiahuihui This version does not support GO pathways because at the time of writing, GO's API structure made it less accessible through R than KEGG's. There is no time line for when diffEnrich will add GO functions, but in the meantime you might try using GOexpress: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-0971-3.
